import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nav } from "./components/nav/page";
import Footer from "./components/nav/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Fixed navigation at the top */}
        <div className="fixed top-0 left-0 right-0 z-50 bg-white shadow-md">
          <Nav />
        </div>

        {/* Main content with top padding to account for fixed nav */}
        <main className="">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
